### ISSUE TITLE
[Bug] Posts no longer federate, can't publish anything

### ISSUE THREAD

**Issue by DeadSuperHero** [jdormit/pterotype#4] opened 2018-11-02 18:23 UTC
After attempting to upgrade to the new version of Pterotype, I ended up in a pretty messy situation where I experienced a WSOD all across my installation. After some poking around, I realized identity.php under the /client directory was missing, so I manually copied the code from the repo to patch it. That got the plugin working again, but now new posts don't federate out, and after making a few attempts to post, I can no longer create new articles.

Turned on debug mode , here's what my logs say:

```
[02-Nov-2018 18:19:15 UTC] WordPress database error Duplicate entry '' for key 'activitypub_id' for query INSERT INTO `wp_pterotype_objects` (`object`) VALUES ('{\"@context\":[\"https:\\/\\/www.w3.org\\/ns\\/activitystreams\"],\"type\":\"Update\",\"a$
[02-Nov-2018 18:19:15 UTC] WordPress database error Cannot add or update a child row: a foreign key constraint fails (`wordpress`.`wp_pterotype_outbox`, CONSTRAINT `wp_pterotype_outbox_ibfk_1` FOREIGN KEY (`object_id`) REFERENCES `wp_pterotype_object$
[02-Nov-2018 18:19:15 UTC] WordPress database error Duplicate entry '' for key 'activitypub_id' for query INSERT INTO `wp_pterotype_objects` (`object`) VALUES ('{\"@context\":[\"https:\\/\\/www.w3.org\\/ns\\/activitystreams\"],\"type\":\"Update\",\"a$
[02-Nov-2018 18:19:15 UTC] WordPress database error Cannot add or update a child row: a foreign key constraint fails (`wordpress`.`wp_pterotype_outbox`, CONSTRAINT `wp_pterotype_outbox_ibfk_1` FOREIGN KEY (`object_id`) REFERENCES `wp_pterotype_object$
```

This probably won't happen when I deploy a new installation to my main domain, but it looks like a botched upgrade may have screwed up my keys.

**Comment by jdormit** [comment] 2018-11-02 20:15
Uh oh. I would hold off deploying to your main domain for now while we
investigate this.

**Comment by DeadSuperHero** [comment] 2018-11-02 20:17
If it helps any, at some point I disabled and re-enabled the Pterotype plugin. Some Wordpress tutorial site offered a workaround to the WSOD problem by renaming the directory of a given plugin.

**Comment by jdormit** [comment] 2018-11-04 13:03
I think you're right that your database has gotten into a weird state - seems like it is trying to create ActivityPub objects that already exist. The weird part is that the unique ActivityPub ids are generated using MySQL's auto-increment columns, which should be universally unique even if you deactivate then reactivate the plugin.

When are these errors triggered? When you publish a new post?

**Comment by DeadSuperHero** [comment] 2018-11-04 22:37
> When are these errors triggered? When you publish a new post?

Yes, any attempts to publish get immediately stopped.

**Comment by jdormit** [comment] 2018-11-04 22:41
Okay, good to know. I'll think it'd be okay to just treat Create activities where the object already exists for some reason as updates rather than insertions. I'm not going to make that change right away though, given the other issues with the latest release (#5).

**Comment by jdormit** [comment] 2018-11-05 03:45
I figured out #5, and it wasn't related to this. I'm going to push out a change tomorrow that make inserting new ActivityPub objects with existing ids into the database work, but I'll `error_log` when that happens so we can try to track how often it's happening for you and maybe figure out how your DB got into this state in the first place.

**Comment by jdormit** [comment] 2018-11-05 11:05
@DeadSuperHero, can you post the full error lines here? I want to see the stack trace/line number of the errors just to make sure I fix the right thing.

**Comment by DeadSuperHero** [comment] 2018-11-05 18:56
No problem, here's the full output for one failed publishing event attempted minutes ago:

```
[05-Nov-2018 18:54:08 UTC] WordPress database error Duplicate entry '' for key 'activitypub_id' for query INSERT INTO `wp_pterotype_objects` (`object`) VALUES ('{\"@context\":[\"https:\\/\\/www.w3.org\\/ns\\/activitystreams\"],\"type\":\"Delete\",\"a$
[05-Nov-2018 18:54:08 UTC] WordPress database error Cannot add or update a child row: a foreign key constraint fails (`wordpress`.`wp_pterotype_outbox`, CONSTRAINT `wp_pterotype_outbox_ibfk_1` FOREIGN KEY (`object_id`) REFERENCES `wp_pterotype_object$
[05-Nov-2018 18:54:23 UTC] PHP Notice:  Trying to get property of non-object in /var/www/staging.wedistribute.org/wp-includes/post-template.php on line 298
[05-Nov-2018 18:54:33 UTC] PHP Notice:  Trying to get property of non-object in /var/www/staging.wedistribute.org/wp-includes/post-template.php on line 298
[05-Nov-2018 18:54:48 UTC] WordPress database error Duplicate entry '' for key 'activitypub_id' for query INSERT INTO `wp_pterotype_objects` (`object`) VALUES ('{\"@context\":[\"https:\\/\\/www.w3.org\\/ns\\/activitystreams\"],\"type\":\"Create\",\"a$
[05-Nov-2018 18:54:48 UTC] WordPress database error Cannot add or update a child row: a foreign key constraint fails (`wordpress`.`wp_pterotype_outbox`, CONSTRAINT `wp_pterotype_outbox_ibfk_1` FOREIGN KEY (`object_id`) REFERENCES `wp_pterotype_object$
[05-Nov-2018 18:54:49 UTC] WordPress database error Duplicate entry '' for key 'activitypub_id' for query INSERT INTO `wp_pterotype_objects` (`object`) VALUES ('{\"@context\":[\"https:\\/\\/www.w3.org\\/ns\\/activitystreams\"],\"type\":\"Update\",\"a$
[05-Nov-2018 18:54:49 UTC] WordPress database error Cannot add or update a child row: a foreign key constraint fails (`wordpress`.`wp_pterotype_outbox`, CONSTRAINT `wp_pterotype_outbox_ibfk_1` FOREIGN KEY (`object_id`) REFERENCES `wp_pterotype_object$
```

**Comment by DeadSuperHero** [comment] 2018-11-05 19:00
Also, if it helps any, here are the steps I took that screwed everything up.

1. Updated to latest version of Ptereotype (As of November 2nd)
2. Get WSOD on Admin as well as all public views
3. Rename pterotype plugin as an easy way to disable it. Plugin gets moved from `pterotype` to a new directory called `pterotype-old`.
4. Get some error messages about `identity.php` under the /client directory was missing.
5. Copy the contents of that file from the repo manually
6. Move the plugin back to the pterotype repo
7. Turn it back on
8. Here we are

Initially, I was able to publish and the content simply wouldn't federate, but now I can't federate at all.

**Comment by jdormit** [comment] 2018-11-07 11:56
Hey @DeadSuperHero, looks like the logs you posted are still truncated at the end (the lines end in `$` and are cut off), so I still can't see the line numbers :disappointed:.

In terms of what you did, I don't see how that could corrupt the database, but maybe something went wrong with the db migrations when you turned it back on. Did you ever delete anything manually from MySQL?

There is another thing you could try - you could update Pterotype to the latest version and then deactivate and uninstall (via the "uninstall" button) the plugin. This will delete all Pterotype data from your installation, so it's sort of the nuclear option, but I would expect that if you then reinstalled and reactivated Pterotype from the plugin repository it would work again. Your Pterotype instance would lose all of its posts and followers (just in the Fediverse, the actual WordPress posts would be fine), but maybe that's okay if this is still just your staging instance.

Let me know what you think of that, and if you could get the un-truncated logs that would be really helpful.

**Comment by mediaformat** [comment] 2018-11-08 06:59
Fresh install
created new user, found on mastodon 
new toot, no toots listed for user

Also: On mastodon the view profile links to https://ptero.urbanwildlife.biz/wp-json/pterotype/v1/actor/bo, which is great for machines, but for really it should link to https://ptero.urbanwildlife.biz/author/bo

**Comment by jdormit** [comment] 2018-11-08 14:36
Did you follow the user on Mastodon? Due to the way the federation protocol
works, posts will only show up in the profile if at least one user on the
instance is following the blog actor. That happens because the blog will
only send Create activities to followers, and Mastodon only knows about the
post if someone sent the Create activity. I have some half-baked thought to
resolve that by keeping a master list of Fediverse servers to send new
posts to, but I'm not sure how/if that would work...

Yeah that URL is definitely not good for humans haha. Putting that on the
roadmap.

**Comment by mediaformat** [comment] 2018-11-08 18:07
Yes, I had followed the user @bo@ptero.urbanwildlife.biz

**Comment by jdormit** [comment] 2018-11-08 20:07
Hrm. Also hearing reports of this from other users. I'll pause other development and focus on figuring out what is going on.

**Comment by jdormit** [comment] 2018-11-08 20:16
So instances that are experiencing problems:

- https://blog.keysmash.xyz/
- https://ptero.urbanwildlife.biz/ (@mediaformat, is there any chance your site is configured with an `http` site URL in the WordPress settings? I noticed the blog is accessible over http and https)
- https://staging.wedistribute.org/

I'm thinking that the federation issues and the DB issues that @DeadSuperHero is experiencing are unrelated, but I'm not sure yet.

**Comment by kvibber** [comment] 2018-11-08 20:49
Detail on blog.keysmash.xyz: It was definitely federating on November 4, and it stopped on November 5. (Unfortunately I didn't notice until today. The good thing is I've been trying to post daily, which made it possible to narrow it down.)  Before I tried uninstalling and reinstalling the plugin, it was able to sync incoming comments from Mastodon, but didn't push anything outward.

It's running the WordPress 5.0 beta, which may or may not be a factor, but when I went to look, I found the same sort of SQL errors in my logs that @DeadSuperHero reported:

```
[Mon Nov 05 17:40:07 2018] [warn] [client 74.62.242.142] mod_fcgid: stderr: WordPress database error Duplicate entry '' for key 'activitypub_id' for query INSERT INTO `keysmash_pterotype_objects` (`object`) VALUES ('{\\"@context\\":[\\"https:\\\\/\\\\/www.w3.org\\\\/ns\\\\/activitystreams\\"],\\"type\\":\\"Update\\",\\"actor\\":\\"https:\\\\/\\\\/blog.keysmash.xyz\\\\/wp-json\\\\/pterotype\\\\/v1\\\\/actor\\\\/-blog\\",\\"object\\":null,\\"to\\":[\\"https:\\\\/\\\\/www.w3.org\\\\/ns\\\\/activitystreams#Public\\",\\"https:\\\\/\\\\/blog.keysmash.xyz\\\\/wp-json\\\\/pterotype\\\\/v1\\\\/actor\\\\/-blog\\\\/followers\\"]}') made by do_action('wp_ajax_inline-save'), WP_Hook->do_action, WP_Hook->apply_filters, wp_ajax_inline_save, edit_post, wp_update_post, wp_insert_post, wp_transition_post_status, do_action('transition_post_status'), WP_Hook->do_action, WP_Hook->apply_filters, pterotype\\posts\\handle_post_status_change, WP_REST_Server->dispatch, pterotype\\api\\post_to_outbox, pterotype\\outbox\\handle_activity, pterotype\\outbox\\persist_activity, pterotype\\objects\\create_local_object, referer: https://blog.keysmash.xyz/wp-admin/edit.php
[Mon Nov 05 17:40:07 2018] [warn] [client 74.62.242.142] mod_fcgid: stderr: WordPress database error Cannot add or update a child row: a foreign key constraint fails (`fedtest_blog`.`keysmash_pterotype_outbox`, CONSTRAINT `keysmash_pterotype_outbox_ibfk_1` FOREIGN KEY (`object_id`) REFERENCES `keysmash_pterotype_objects` (`id`)) for query INSERT INTO `keysmash_pterotype_outbox` (`actor_id`, `object_id`) VALUES ('3', 0) made by do_action('wp_ajax_inline-save'), WP_Hook->do_action, WP_Hook->apply_filters, wp_ajax_inline_save, edit_post, wp_update_post, wp_insert_post, wp_transition_post_status, do_action('transition_post_status'), WP_Hook->do_action, WP_Hook->apply_filters, pterotype\\posts\\handle_post_status_change, WP_REST_Server->dispatch, pterotype\\api\\post_to_outbox, pterotype\\outbox\\handle_activity, pterotype\\outbox\\persist_activity, referer: https://blog.keysmash.xyz/wp-admin/edit.php
[Mon Nov 05 17:40:29 2018] [warn] [client 74.62.242.142] mod_fcgid: stderr: WordPress database error Duplicate entry '' for key 'activitypub_id' for query INSERT INTO `keysmash_pterotype_objects` (`object`) VALUES ('{\\"@context\\":[\\"https:\\\\/\\\\/www.w3.org\\\\/ns\\\\/activitystreams\\"],\\"type\\":\\"Update\\",\\"actor\\":\\"https:\\\\/\\\\/blog.keysmash.xyz\\\\/wp-json\\\\/pterotype\\\\/v1\\\\/actor\\\\/-blog\\",\\"object\\":null,\\"to\\":[\\"https:\\\\/\\\\/www.w3.org\\\\/ns\\\\/activitystreams#Public\\",\\"https:\\\\/\\\\/blog.keysmash.xyz\\\\/wp-json\\\\/pterotype\\\\/v1\\\\/actor\\\\/-blog\\\\/followers\\"]}') made by do_action('wp_ajax_inline-save'), WP_Hook->do_action, WP_Hook->apply_filters, wp_ajax_inline_save, edit_post, wp_update_post, wp_insert_post, wp_transition_post_status, do_action('transition_post_status'), WP_Hook->do_action, WP_Hook->apply_filters, pterotype\\posts\\handle_post_status_change, WP_REST_Server->dispatch, pterotype\\api\\post_to_outbox, pterotype\\outbox\\handle_activity, pterotype\\outbox\\persist_activity, pterotype\\objects\\create_local_object, referer: https://blog.keysmash.xyz/wp-admin/edit.php
[Mon Nov 05 17:40:29 2018] [warn] [client 74.62.242.142] mod_fcgid: stderr: WordPress database error Cannot add or update a child row: a foreign key constraint fails (`fedtest_blog`.`keysmash_pterotype_outbox`, CONSTRAINT `keysmash_pterotype_outbox_ibfk_1` FOREIGN KEY (`object_id`) REFERENCES `keysmash_pterotype_objects` (`id`)) for query INSERT INTO `keysmash_pterotype_outbox` (`actor_id`, `object_id`) VALUES ('3', 0) made by do_action('wp_ajax_inline-save'), WP_Hook->do_action, WP_Hook->apply_filters, wp_ajax_inline_save, edit_post, wp_update_post, wp_insert_post, wp_transition_post_status, do_action('transition_post_status'), WP_Hook->do_action, WP_Hook->apply_filters, pterotype\\posts\\handle_post_status_change, WP_REST_Server->dispatch, pterotype\\api\\post_to_outbox, pterotype\\outbox\\handle_activity, pterotype\\outbox\\persist_activity, referer: https://blog.keysmash.xyz/wp-admin/edit.php
```

Those are the first two errors of that sort. There aren't any of them before my last successful federation test on November 4, and there are a lot of them now.

**Comment by kvibber** [comment] 2018-11-08 21:01
Interesting: Because the delete link on the plugin screen failed, I manually deleted the files and database tables in order to reinstall it cleanly this morning. When I re-installed the plugin, it didn't re-create the database tables.

I'm not certain, but I think this might be the error from when I tried to uninstall through the dashboard (before I removed the tables manually):

```
[Thu Nov 08 10:56:12 2018] [warn] [client 74.62.242.142] mod_fcgid: stderr: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function wpdb::prepare(), 1 passed in /home/kv_keysmasher/blog.keysmash.xyz/wp-content/plugins/pterotype/includes/server/actors.php on line 19 and exactly 2 expected in /home/kv_keysmasher/blog.keysmash.xyz/wp-includes/wp-db.php:1222, referer: https://blog.keysmash.xyz/wp-admin/plugins.php?plugin_status=all&paged=1&s
```

**Comment by kvibber** [comment] 2018-11-08 21:36
OK! After removing all the pterotype options from the options table, I was able to reactivate it and get it to re-create the tables. It's working again: I'm able to follow from Mastodon, see posts more or less instantly, see the updated profile, etc.

Older posts no longer sync comments, but newer ones do, which I was kind of expecting.

**Comment by jdormit** [comment] 2018-11-08 22:04
@kvibber thanks, that is super helpful! I'm going to take a close look at this ASAP (hopefully by the end of the week, or over the weekend for sure).

**Comment by jdormit** [comment] 2018-11-08 22:18
Also, it's interesting to me that manually deleting all the Pterotype data and starting from scratch fixed the issue - it makes me hopeful that it's no longer possible to get into this state in the latest version. Looking into those stack traces will help me confirm or deny, though.

**Comment by jdormit** [comment] 2018-11-09 11:02
A couple things I notice right off the bat about @kvibber's stack trace:

- it's trying to save an Update activity will a `null` object and an empty ID (`activitypub_id = ''`). 
  This is happening on post creation, in the `transition_post_status` hook when Pterotype tries to create a new ActivityPub object to represent the post.
- this would be the direct cause of the next error, a constraint violation when Pterotype tries to add the object to the outbox: since the object was never created, there's no `object_id` to save to the `outbox` table.

So the next question is, why isn't the Update activity getting populated with the correct `object` and `id`?

**Comment by jdormit** [comment] 2018-11-09 11:15
~Okay, I've reproduced this bug. This happens when you update a post via "Quick edit" from the posts table. Now I'm looking into why and how we can fix it.~

I was wrong about what causes this. I don't have a full understanding yet, but what is happening is that somehow an object is getting saved to the objects table without an activitypub id, and never gets assigned one. When Pterotype makes a new object, it does so in two steps - first it puts the object into the db so that MySQL can assign it an ID, then it updates that object with an activitypub id based on the assigned id. However, the first step can fail if there's another object in the DB that doesn't have an activitypub id, which causes the errors you posted and prevents the object from getting created, meaning posts won't federate.

I'm having trouble reproducing the conditions that lead to an object getting created without an activitypub id and not getting updated, but I am working on a way to create new objects that won't face this problem.

**Comment by jdormit** [comment] 2018-11-09 13:36
Okay, I shipped out an update (1.2.7) that should prevent these errors - basically, instead of attempting to save the post with an empty `activitypub_id`, it first saves it with a random number there and then overwrites that with the actual id when it generates it. That prevents collisions on the `''` value.

@DeadSuperHero, if you update to the latest version of Pterotype, do the errors go away?

**Comment by DeadSuperHero** [comment] 2018-11-09 18:39
Yes, it works! Federation is up and running again.

**Comment by jdormit** [comment] 2018-11-09 18:42
Wooo! 🎉

**Comment by mediaformat** [comment] 2018-11-10 14:44
Still not working for me.

Here’s what I’ve done so far:
- updated to 1.2.7
- forced https
- deactivated, reactivated plug-in
- added a new user with a longer slug (@moncai@ptero.urbanwildlife.biz), followed on masto, posted, and no toots shown.

I’ll check the logs later to see what gives, and report back.

**Comment by mediaformat** [comment] 2018-11-10 19:34
So the logs are showing that federation is coming from mastodon.social
Specifically it looks like seen some delete user actions. 

I could see the logs growing quickly here. Perhaps there could be some kind of check, that said user has either followed a user on my ´instance’, or that they have commented on a toot/post.

´[10-Nov-2018 06:37:51 UTC] WordPress database error Duplicate entry 'https://mastodon.social/users/Arcaire#delete' for key 'activitypub_id' for query INSERT INTO `865_pterotype_objects` (`activitypub_id`, `type`, `object`, `url`) VALUES ('https://mastodon.social/users/Arcaire#delete', 'Delete', '{\"@context\":[\"https:\\/\\/www.w3.org\\/ns\\/activitystreams\",\"https:\\/\\/w3id.org\\/security\\/v1\",{\"manuallyApprovesFollowers\":\"as:manuallyApprovesFollowers\",\"sensitive\":\"as:sensitive\",\"movedTo\":{\"@id\":\"as:movedTo\",\"@type\":\"@id\"},\"Hashtag\":\"as:Hashtag\",\"ostatus\":\"http:\\/\\/ostatus.org#\",\"atomUri\":\"ostatus:atomUri\",\"inReplyToAtomUri\":\"ostatus:inReplyToAtomUri\",\"conversation\":\"ostatus:conversation\",\"toot\":\"http:\\/\\/joinmastodon.org\\/ns#\",\"Emoji\":\"toot:Emoji\",\"focalPoint\":{\"@container\":\"@list\",\"@id\":\"toot:focalPoint\"},\"featured\":{\"@id\":\"toot:featured\",\"@type\":\"@id\"},\"schema\":\"http:\\/\\/schema.org#\",\"PropertyValue\":\"schema:PropertyValue\",\"value\":\"schema:value\"}],\"id\":\"https:\\/\\/mastodon.social\\/users\\/Arcaire#delete\",\"type\":\"Delete\",\"actor\":\"https:\\/\\/mastodon.social\\/users\\/Arcaire\",\"to\":[\"https:\\/\\/www.w3.org\\/ns\\/activitystreams#Public\"],\"object\":\"https:\\/\\/mastodon.social\\/users\\/Arcaire\",\"signature\":{\"type\":\"RsaSignature2017\",\"creator\":\"https:\\/\\/mastodon.social\\/users\\/Arcaire#main-key\",\"created\":\"2018-11-10T06:37:39Z\",\"signatureValue\":\"itQTEDFF84jqdnxnMeuxRmBiDtIektNxJnG0LEyZSwnlepMIOnim4NgCzZI5+9mjY7\\/Gw3QIz\\/HA7HECnKL7nhWaiL8i\\/QXRGdgZ2Zo7PdNdUktQGukIyqhr7FUIqNfRhN9buhBllymJZF0Mnm0VQZ0AcoG46fzVoJXIEysGc3VMOXFo\\/g0nVNiPxlFBKz8bHE2KPZ+SowJUNSLKemSXrnUgF24nwmlX+95K6coJg5U0tup7UKBzOVrzp7+Qw2HW48dqNywdlxI6991cF9KXjLNUpAFSX1196NU1aMsDS7ACSdhNtyjEJ4VjQGq73O94seCLFx4VkUp+6fAH4if3yw==\"}}', '') made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, pterotype\api\post_to_inbox, pterotype\inbox\handle_activity, pterotype\inbox\persist_activity, pterotype\objects\upsert_object /public_html/www/ptero/wp-admin/error_log: [08-Nov-2018 06:51:01 UTC] WordPress database error Cannot add foreign key constraint for query CREATE TABLE 865_pterotype_comments ( comment_id BIGINT(20) UNSIGNED NOT NULL, object_id INT UNSIGNED NOT NULL, PRIMARY KEY (comment_id, object_id), FOREIGN KEY pt_comments_comment_fk(comment_id) REFERENCES 865_comments(comment_ID), FOREIGN KEY pt_comments_object_fk(object_id) references 865_pterotype_objects(id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; made by activate_plugin, do_action('activate_pterotype/pterotype.php'), WP_Hook->do_action, WP_Hook->apply_filters, pterotype_init, do_action('pterotype_init'), WP_Hook->do_action, WP_Hook->apply_filters, pterotype\init\{closure}, pterotype\schema\run_migrations, pterotype\schema\apply_migration, call_user_func, pterotype\schema\migration_1_1_0´

**Comment by mediaformat** [comment] 2018-11-11 00:25
So the logs are showing that federation is coming from mastodon.social
Specifically it looks like seen some delete user actions.

I could see the logs growing quickly here. Perhaps there could be some kind of check, that said user has either followed a user on my ´instance’, or that they have commented on a toot/post.

Repost to remove identifiers
`[10-Nov-2018 06:37:51 UTC] WordPress database error Duplicate entry 'https://mastodon.social/users/XXXX#delete' for key 'activitypub_id' for query INSERT INTO 865_pterotype_objects (activitypub_id, type, object, url) VALUES ('https://mastodon.social/users/XXXX#delete', 'Delete', '{"@context":["https:\/\/www.w3.org\/ns\/activitystreams","https:\/\/w3id.org\/security\/v1",{"manuallyApprovesFollowers":"as:manuallyApprovesFollowers","sensitive":"as:sensitive","movedTo":{"@id":"as:movedTo","@type":"@id"},"Hashtag":"as:Hashtag","ostatus":"http:\/\/ostatus.org#","atomUri":"ostatus:atomUri","inReplyToAtomUri":"ostatus:inReplyToAtomUri","conversation":"ostatus:conversation","toot":"http:\/\/joinmastodon.org\/ns#","Emoji":"toot:Emoji","focalPoint":{"@container":"@list","@id":"toot:focalPoint"},"featured":{"@id":"toot:featured","@type":"@id"},"schema":"http:\/\/schema.org#","PropertyValue":"schema:PropertyValue","value":"schema:value"}],"id":"https:\/\/mastodon.social\/users\/XXXX#delete","type":"Delete","actor":"https:\/\/mastodon.social\/users\/XXXX","to":["https:\/\/www.w3.org\/ns\/activitystreams#Public"],"object":"https:\/\/mastodon.social\/users\/XXXX","signature":{"type":"RsaSignature2017","creator":"https:\/\/mastodon.social\/users\/XXXX#main-key","created":"2018-11-10T06:37:39Z","signatureValue":"REDACTED"}}', '') made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, pterotype\api\post_to_inbox, pterotype\inbox\handle_activity, pterotype\inbox\persist_activity, pterotype\objects\upsert_object /public_html/www/ptero/wp-admin/error_log: [08-Nov-2018 06:51:01 UTC] WordPress database error Cannot add foreign key constraint for query CREATE TABLE 865_pterotype_comments ( comment_id BIGINT(20) UNSIGNED NOT NULL, object_id INT UNSIGNED NOT NULL, PRIMARY KEY (comment_id, object_id), FOREIGN KEY pt_comments_comment_fk(comment_id) REFERENCES 865_comments(comment_ID), FOREIGN KEY pt_comments_object_fk(object_id) references 865_pterotype_objects(id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; made by activate_plugin, do_action('activate_pterotype/pterotype.php'), WP_Hook->do_action, WP_Hook->apply_filters, pterotype_init, do_action('pterotype_init'), WP_Hook->do_action, WP_Hook->apply_filters, pterotype\init{closure}, pterotype\schema\run_migrations, pterotype\schema\apply_migration, call_user_func, pterotype\schema\migration_1_1_0`

**Comment by kvibber** [comment] 2018-11-11 00:53
I'm still having issues too, even with 1.2.8. After unfollowing & refollowing the blog, I'm able to see new *posts* showing up in Mastodon, and replies from Mastodon are syncing to the blog, but comments on the blog aren't being sent out.

I'm seeing a lot of these in error_log:

```
[Sat Nov 10 16:21:25 2018] [warn] [client 195.201.111.25] mod_fcgid: stderr: WordPress database error Column 'actor_id' cannot be null for query INSERT INTO `keysmash_pterotype_inbox` (`actor_id`, `object_id`) VALUES (NULL, 123) made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, pterotype\\api\\post_to_inbox, pterotype\\inbox\\handle_activity, pterotype\\inbox\\persist_activity
```

**Comment by jdormit** [comment] 2018-11-11 02:57
Hmm... Reopening this, clearly things are still broken.

**Comment by jdormit** [comment] 2018-11-11 13:32
Okay, I'm seeing a few separate issues in the stack traces here:

1. In the first trace in @mediaformat's comment, Pterotype attempts to persist an activity that it already has the the DB. This is a bug - the expected behavior there is that the plugin sees that is already persisted the activity and does not attempt to do so again.
2. In the second trace in @mediaformat's comment, the schema migration fails when it tries to create the (pterotype) comments table. This would explain why federation isn't working for you - Pterotype isn't able to access the DB tables it needs because they can't be created. I recommend deactivating + fully deleting Pterotype, which will reset the DB to its initial state, and see if those errors go away.
3. In @kvibber's comment, Pterotype receives an activity to its inbox and attempts to save the inbox entry, but the `actor_id` of the inbox is `null` for some reason. That gets parsed from the URL of the request to the inbox - is there any way for you tell what the URL of this request was?

**Comment by jdormit** [comment] 2018-11-11 14:38
Alright, made a few changes:
- https://github.com/jdormit/pterotype/commit/3e6ddf96b6ed674be0f2bb0abdb32b450941453c adds a check to make sure the actor actually exists before handling requests to the outbox/inbox, which will prevent the errors that @kvibber was seeing. I'd still like to know what requests are triggering those `null` values for `actor_id`, though.
- https://github.com/jdormit/pterotype/commit/4d73cf1e5edaaff756919e4168d08b6ac03e611f refactors the `upsert_object` function to use a method which I think will eliminate the `duplicate entry` errors that @mediaformat was seeing.

**Comment by jdormit** [comment] 2018-11-11 15:05
The above change are deployed to the plugin repo as version 1.2.9. When you all have a chance, I'd appreciate it if you'd try it out and let me know if your issues (or some of them) are resolved.

**Comment by jdormit** [comment] 2018-11-11 15:21
Update: I installed Pterotype on my personal blog and Mastodon is failing to find it, despite it successfully making a WebFinger request and a request for the blog actor. Sounds similar to problems @mediaformat is having. So that's the next place I'll investiage.

**Comment by kvibber** [comment] 2018-11-11 20:20
OK, two things:  The actor_id errors are all on requests from mastodon.cloud, which I find interesting, with the following pattern:

```
195.201.111.25 - - [11/Nov/2018:02:49:05 -0800] "POST /wp-json/pterotype/v1/actor/MaxMercury_mastodon_cloud/inbox HTTP/1.1" 500 4135 "-" "http.rb/3.3.0 (Mastodon/2.6.1; +https://mastodon.cloud/)" 
195.201.111.25 - - [11/Nov/2018:02:49:09 -0800] "POST /wp-json/pterotype/v1/actor/not_me_example_com/inbox HTTP/1.1" 500 4135 "-" "http.rb/3.3.0 (Mastodon/2.6.1; +https://mastodon.cloud/)" 
195.201.111.25 - - [11/Nov/2018:02:49:22 -0800] "POST /wp-json/pterotype/v1/actor/guest_with_website/inbox HTTP/1.1" 500 4135 "-" "http.rb/3.3.0 (Mastodon/2.6.1; +https://mastodon.cloud/)" 
195.201.111.25 - - [11/Nov/2018:02:49:29 -0800] "POST /wp-json/pterotype/v1/actor/guest/inbox HTTP/1.1" 500 4135 "-" "http.rb/3.3.0 (Mastodon/2.6.1; +https://mastodon.cloud/)" 
```

These all appear to be stemming from a test post I did before the uninstall/reinstall. The first is a test user I have on mastodon.cloud, while the other three are guest commenters on the blog itself.

Second thing:
I had another set of errors that I thought was unrelated because it reported the include file instead of the request file:

```
[Sun Nov 11 01:04:37 2018] [warn] [client 159.203.165.12] mod_fcgid: stderr: PHP Fatal error:  Allowed memory size of 94371840 bytes exhausted (tried to allocate 20480 bytes) in /home/kv_keysmasher/blog.keysmash.xyz/wp-includes/rest-api/class-wp-rest-server.php on line 736
```

But the request that was on was
```
159.203.165.12 - - [11/Nov/2018:01:03:55 -0800] "POST /wp-json/pterotype/v1/actor/-blog/inbox HTTP/1.1" 500 3908 "-" "http.rb/3.2.0 (Mastodon/2.4.3; +https://wandering.shop/)" 
```

I added some memory to PHP in the php.ini file, and did another test post. Everything worked this time: the post was broadcast to Wandering.shop, the reply on WS went back to the blog, and comments on the blog, both from the author and guest comments, went out to Mastodon and were visible on the comment thread there!

**Comment by mediaformat** [comment] 2018-11-12 01:41
So I deleted 1.2.8

Installed 1.2.9

And this what logged:
`[11-Nov-2018 23:21:18 UTC] PHP Warning:  Missing argument 2 for wpdb::prepare(), called in /public_html/www/ptero/wp-content/plugins/pterotype/includes/server/actors.php on line 19 and defined in /public_html/www/ptero/wp-includes/wp-db.php on line 1222`

`[11-Nov-2018 23:21:20 UTC] PHP Warning:  Missing argument 2 for wpdb::prepare(), called in /public_html/www/ptero/wp-content/plugins/pterotype/includes/schema.php on line 315 and defined in /public_html/www/ptero/wp-includes/wp-db.php on line 1222`

`[11-Nov-2018 23:21:20 UTC] PHP Warning:  Missing argument 2 for wpdb::prepare(), called in /public_html/www/ptero/wp-content/plugins/pterotype/includes/schema.php on line 324 and defined in /public_html/www/ptero/wp-includes/wp-db.php on line 1222`

`[11-Nov-2018 23:21:20 UTC] WordPress database error Unknown table 'urbanwi6_865.865_pterotype_comments' for query 
        DROP TABLE 865_pterotype_comments, 865_pterotype_keys,
            865_pterotype_blocks, 865_pterotype_shares,
            865_pterotype_following, 865_pterotype_followers,
            865_pterotype_actor_likes, 865_pterotype_object_likes,
            865_pterotype_outbox, 865_pterotype_inbox,
            865_pterotype_actors, 865_pterotype_objects
         made by do_action('wp_ajax_delete-plugin'), WP_Hook->do_action, WP_Hook->apply_filters, wp_ajax_delete_plugin, delete_plugins, uninstall_plugin, do_action('uninstall_pterotype/pterotype.php'), WP_Hook->do_action, WP_Hook->apply_filters, pterotype_uninstall, do_action('pterotype_uninstall'), WP_Hook->do_action, WP_Hook->apply_filters, pterotype\init\{closure}, pterotype\schema\purge_all_data`

`[11-Nov-2018 23:21:55 UTC] WordPress database error Cannot add foreign key constraint for query 
       CREATE TABLE 865_pterotype_comments (
           comment_id BIGINT(20) UNSIGNED NOT NULL,
           object_id INT UNSIGNED NOT NULL,
           PRIMARY KEY (comment_id, object_id),
           FOREIGN KEY pt_comments_comment_fk(comment_id)
               REFERENCES 865_comments(comment_ID),
           FOREIGN KEY pt_comments_object_fk(object_id)
               references 865_pterotype_objects(id)
       )
       ENGINE=InnoDB DEFAULT CHARSET=utf8;
        made by activate_plugin, do_action('activate_pterotype/pterotype.php'), WP_Hook->do_action, WP_Hook->apply_filters, pterotype_init, do_action('pterotype_init'), WP_Hook->do_action, WP_Hook->apply_filters, pterotype\init\{closure}, pterotype\schema\run_migrations, pterotype\schema\apply_migration, call_user_func, pterotype\schema\migration_1_1_0`

Unfollowed, refollowed, 2 wp accounts, from 2 different masto instances.
Posted from both wp accounts. 
Nada thing.

Will retry the plugin installation again.

**Comment by mediaformat** [comment] 2018-11-12 02:30
Retried install, and got the same errors, noticed I had a cache system enabled.

Removed cache system, Retried delete & reinstall, and the log errors have ceased.

But federation is still not working.

**Comment by jdormit** [comment] 2018-11-12 13:22
@kvibber awesome! Glad things are working for you now :smile: 

I figured out the cause of the issues on my own blog: I had Apache URL rewrites configured incorrectly, which was causing my server to respond to WebFinger requests with a nonsensical value. Once I fixed that, discovery worked fine.

@mediaformat I found your blog user on mastodon.technology by searching for "@blog@ptero.urbanwildlife.biz" in the search bar:

![image](https://user-images.githubusercontent.com/6351890/48350049-f6ace480-e653-11e8-9a96-d42bf1e2a5cb.png)

I was also able to successfully follow the blog, which makes me think that federation is working. When you get a chance, could you post something to that blog so we can see if it shows up in my feed?

**Comment by mediaformat** [comment] 2018-11-12 22:20
Yess, following @blog worked!

**Comment by mediaformat** [comment] 2018-11-12 22:31
Has everyone been using @blog this whole time, and I was trying to get @user addresses to work, lol?

**Comment by jdormit** [comment] 2018-11-13 14:55
Oh man, yup. Honestly that's my bad, seeing as Pterotype doesn't have any documentation...

Sounds like these issues are resolved for everyone involved now. I'm going to close this out again.

**Closed as completed by jdormit** 2018-11-13 14:55 UTC
