### ISSUE TITLE
[Feature Request] Use Article activity type instead of Note

### ISSUE THREAD

**Issue by DeadSuperHero** [jdormit/pterotype#2] opened 2018-10-29 17:27 UTC
Currently, Pterotype uses the `Note` activity type to make a little status on the Mastodon / Pleroma side of things. This is perfectly acceptable for brief statuses with link previews, but the caveat is that some ActivityPub platforms (Pleroma, Plume) can support full-blown articles with HTML formatting.

Given that we probably want broader compatibility here, would the following logic make sense?

1. If a client doesn't support the `Article` type, fall back to a `Note`
2. If a client _does_ support `Article`, provide the full `Article` object instead

**Comment by jdormit** [comment] 2018-10-29 18:43
> If a client doesn't support the Article type, fall back to a Note

This is really interesting, I hadn't thought about that. What do you think the best way to implement that would be? I think Mastodon at least has some info in its response headers that identify it. Or maybe there is something in the `@context` of the Actor that identifies what platform it is on?

So the logic would look something like this: when publishing an Activity, check the inbox URL we are about to send to. Make a request to this URL to inspect the response headers (and cache the response in the DB to avoid making unnecessary requests), or check the Actor `@context` if that route makes more sense. Then we can decide what type of Object to send out.

I would want to make this an extensible system so that we could have custom ActivityPub representations for many different platforms - so we'll need a way to identify different platforms based on the inbox URL/Actor object and a handler for each platform (plus a generic one for unrecognized/unidentifiable platforms). This could be really cool in the future, since it would let us send videos to PeerTube, images to PixelFed, etc., assuming those media types are present in the blog post.

**Comment by jalcine** [comment] 2018-10-29 21:53
This is me not knowing too much about clients but can you query a client to determine what types they support? Or would one have to do a match against the user agent to determine this?

**Comment by kaniini** [comment] 2018-10-29 21:58
activitypub has zero capability negotiation.  there is some concept of a "compound activity type" (yeah, because on top of the 250+ ones we don't use, we need compounding too).  but no implementation to my knowledge actually supports those.

i would suggest sending as article and banging gargron's head against the wall until he gives you a decent rendering.

**Comment by agateblue** [comment] 2018-10-29 21:59
I'd say you should send the type most suited for your content (Article in this case?), and let various applications handle the fallback to the proper content type if they need too (replace Article by Note for Mastodon, etc.)

**Comment by DeadSuperHero** [comment] 2018-10-29 22:00
> i would suggest sending as article and banging gargron's head against the wall until he gives you a decent rendering.

Maybe the sane workaround here would be to default to `Article`, and Mastodon in turn can render unsupported activity types as `Note`?

**Comment by DeadSuperHero** [comment] 2018-10-29 22:00
Ah, I see @EliotBerriot beat me to it. ;)

**Comment by mariusor** [comment] 2018-10-29 22:01
I think [this PR](https://github.com/tootsuite/mastodon/pull/9121) that was merged yesterday is a first step for Mastodon to support Article objects.

**Comment by mariusor** [comment] 2018-10-29 22:05
> I would want to make this an extensible system so that we could have custom ActivityPub representations for many different platforms

I think that is very much against what ActivityPub as a standard represents. You should not encourage non-compliant applications to keep being that way. 

Also the number of requests for disseminating an AP Activity is high enough as it is if you have multiple inboxes to send to, if you require multiple round-trips to each instance that those inboxes belong to it's probably going to get untenable.

**Comment by DeadSuperHero** [comment] 2018-10-29 22:39
Given current discussions, it sounds like the most reasonable approach here would be to just send `Article`, and let individual platforms render them however they want. It may not look like the best thing in the world right now @jdormit , but in time platforms can properly implement support for it.

Part of the problem here is that Mastodon isn't supporting `Article` in a way that conforms with how content on their platform looks. That being said, it sounds like Gargron is very amenable towards making adjustments so that it'll look better in a future release.

**Comment by Halfwake** [comment] 2018-10-29 22:52
Could we give both messages the same ID and send them with the Article format first and then the Note format? Hoped for behavior is as follows.
- If Article object is supported, the client will process it. If the client gets another message with the same ID, it'll be dropped.

- If the Article object cannot be handled, the client will drop it and forget the ID ever existed. If the client receives a Note object afterwards, it'll process it.

If possible, this would be a general way of supporting downgrading. Just send messages with the same ID and different formats starting with the preferred format and downgrading.

I haven't looked at the specification for a while, so I'm not sure how realistic this is. I suspect it somehow breaks forwarding between instances.

**Comment by jdormit** [comment] 2018-10-29 22:57
I've thought about it, and I'm in favor of just sending an Article type for
posts and a Note for comments. The problem isn't that Mastodon rejects the
Article - it just displays it in a stupid way. I may look into PRing
Mastodon to make it display Articles more reasonably.

**Comment by mbajur** [comment] 2018-10-30 07:06
> I think this PR that was merged yesterday is a first step for Mastodon to support Article objects.

@mariusor i would not name it like that - this PR is rather about making a Page object handled the same way as Article - converting it to note with excerpt and link to linked page, nothing more :)

**Comment by jdormit** [comment] 2018-10-30 09:50
@mbajur any thoughts about displaying Article/Page in Mastodon in a more helpful way? My main problem is setting the `summary` as the CW text and the `name` as the body, with a link to the content -- it would be much more useful IMO to display the `name` as the CW and the `summary` as the body.

**Comment by jdormit** [comment] 2018-10-30 10:22
@mbajur or better yet, don't put the content behind a CW at all - just display the `name` and the `summary` in the post body with a link to the `url` at the bottom (and link preview).

**Comment by elegaanz** [comment] 2018-10-30 11:48
Here is an issue to improve the way `Article` are displayed in Mastodon: https://github.com/tootsuite/mastodon/issues/8609

**Comment by jdormit** [comment] 2018-10-30 12:59
cb3e30184650a9e13121e548af79ddce71c21f3d restores posts' ActivityPub representation to use the `Article` type. I'll leave this issue open until the change makes it into a release.

**Comment by jdormit** [comment] 2018-11-01 09:55
This was released in 1.2.0.

**Closed as completed by jdormit** 2018-11-01 09:55 UTC
Labels: enhancement
